apiVersion: v2
name: polardbx-logcollector
description: Helm chart of polardbx-operator logcollector plugin
type: application
version: 1.6.1
appVersion: v1.6.1
keywords:
  - polardb-x
  - operator
  - logcollector
home: https://www.aliyun.com/product/drds
sources:
  - https://github.com/ApsaraDB/galaxykube