apiVersion: v2
name: polardbx-operator
description: Helm chart of polardbx-operator
type: application
version: 1.2.1
appVersion: v1.2.1
keywords:
- polardb-x
- operator
home: https://www.aliyun.com/product/drds
sources:
- https://github.com/ApsaraDB/galaxykube